apiVersion: v1
kind: Service
metadata:
  name: webhooks-service-loadbalancer
spec:
  selector:
    app: webhooks-service-loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 443
  type: LoadBalancer
