apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-gateway
  name: nginx-gateway
  namespace: default
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"nginx-gateway-backendconfig"}}'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-gateway
  type: NodePort
