apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-gateway
  name: nginx-gateway
  namespace: default
  annotations: null
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-gateway
  type: LoadBalancer
